### ISSUE TITLE
s3args issue

### ISSUE THREAD

**Issue by tianyi-brightbeam** [vladcosorg/action-s3-cloudfront-smart-deploy#19]
Hi, 

Thanks for the action. it works great. except when I I use the `s3args` option.

Here is my config
```yml
      - name: Upload changes to S3 and issue Cloudfront invalidations
        uses: vladcosorg/action-s3-cloudfront-smart-deploy@v1
        with:
          source: dist/
          target: "s3://${{ secrets.S3_BUCKET}}/"
          s3args: --delete --exact-timestamps
          distribution: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID}}
```

But it dose not remove the files I dont have at source, or newly built files.
And looked at my github action log it still runs using the default flags.

```
/usr/local/bin/aws s3 sync dist/ s3://***/ --no-progress --size-only
```
also here's a screenshot of my github action log

<img width="669" alt="Screenshot 2024-01-29 at 15 42 10" src="https://github.com/vladcosorg/action-s3-cloudfront-smart-deploy/assets/148770790/b61b96e2-88f2-4899-918e-288c840256b7">
